### ISSUE TITLE
validDestination modifier

### ISSUE THREAD

**Issue by marceljay** [ConsenSys/smart-contract-best-practices#264]
Is the[ proposed modifier ](https://consensys.github.io/smart-contract-best-practices/tokens/) for valid destinations still considered a best practice? 

The only downside I see is increased gas, but I do not have the perception it's commonly implemented.
```
 modifier validDestination( address to ) {
        require(to != address(0x0));
        require(to != address(this) );
        _;
    }
 ```

**Comment by dmuhs** [comment]
Hey Marcel! I'm currently spending my time between audits to revamp the best practices. The code samples especially are in dire need of some love. 😄  You are correct about the increased gas usage, and while lots of projects solve this issue by inlining these requirements, just as many neglect the `address(this)` check.

[There](https://www.reddit.com/r/ethereum/comments/sfz4kw/did_i_just_lose_half_a_million_dollars_by_sending/) are [a](https://www.reddit.com/r/Metamask/comments/r28scn/weth_sent_to_contract_address_instead_of_wallet/) lot [of](https://www.reddit.com/r/polygonnetwork/comments/pucg7s/help_i_sent_weth_to_the_weth_contract_address/) examples [around](https://www.reddit.com/r/ethereum/comments/onupj4/i_sent_790111_to_this_usdc_contract_address_by/) where [users](https://www.reddit.com/r/ethereumnoobies/comments/i85mqn/how_to_recover_my_eth/) lost [their](https://ethereum.stackexchange.com/questions/34559/i-accidentally-sent-a-token-to-a-token-contract-can-i-get-it-back) funds.

This issue is not always given when the `address(this)` check is missing, e.g., when the contract allows owners to withdraw accidentally sent ETH/tokens and manually refund people. However, this introduces additional trust into the owning entity. Designing a trustless refund mechanism would be too expensive, so a simple revert informing the user of their mistake is the easiest way to go.

**Comment by marceljay** [comment]
Awesome. In the end I implemented the checks for our contracts (toucan.earth), I think especially `address(this)` has immense value :)

**Comment by dmuhs** [comment]
Glad you found it helpful! Closing this issue.
