### ISSUE TITLE
good before bad?

### ISSUE THREAD

**Issue by drandreaskrueger** [ConsenSys/smart-contract-best-practices#45]
Excellent article, thank you very much.

I read somewhere that it is didactically better to first mention the good example, and only then show the bad example - because then the probability is lower that human memory falsely stores the bad example as the way to do it. 

just an idea.

**Comment by nemild** [comment]
Hi @drandreaskrueger, thanks. Currently, it's written this way because many Solidity programmers are writing problematic code, which they need to change. As such, I chose to go from what they might know (the bad) to the good. 

Over time, it's debatable what the ideal order is once the bad is no longer a habit - and it's likely that we'll refactor the *Recommendations* section to highlight the right way to do things and then show the bad way (or even collapse the bad way). The *Known Attacks* section will likely always be in bad /good order, as we are focusing on the attack.

If you feel strongly about this and have empirical justification, I might also highlight your point to other popular repos, like the [Airbnb JS Style Guide](https://github.com/airbnb/javascript from which our doc draws inspiration.

**Comment by drandreaskrueger** [comment]
>  it's written this way because

I understand.

> empirical justification

I hat shortly tried to find such literature, but gave up. That's why the "I read somewhere..." :-)

>  I might also highlight your point 

Very good. Go ahead. Myself, I have not read that other one, and currently have no need.


> If you feel strongly

I don't.   
It was just a thought when after reading I was wondering how to contribute.

This is a good time to learn Solidity, now that best practices are found and described. 

Keep up the good work!
